-- Create USERS table
CREATE TABLE USERS (
  ID          NUMBER         NOT NULL,
  USERNAME    VARCHAR2(100)  NOT NULL,
  EMAIL       VARCHAR2(255)  NOT NULL,
  FIRST_NAME  VARCHAR2(100),
  LAST_NAME   VARCHAR2(100),
  IS_ACTIVE   NUMBER         DEFAULT 1 NOT NULL,
  CREATED_AT  DATE,
  UPDATED_AT  DATE,
  CONSTRAINT pk_users PRIMARY KEY (ID),
  CONSTRAINT uq_users_username UNIQUE (USERNAME),
  CONSTRAINT uq_users_email    UNIQUE (EMAIL)
);

-- Sequence for auto-incrementing IDs
CREATE SEQUENCE users_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Trigger to auto-populate ID from sequence
CREATE OR REPLACE TRIGGER users_bir
  BEFORE INSERT ON USERS
  FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := users_seq.NEXTVAL;
END;
/

-- Seed data
INSERT INTO USERS (USERNAME, EMAIL, FIRST_NAME, LAST_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES ('johndoe', 'john.doe@example.com', 'John', 'Doe', 1, SYSDATE, SYSDATE);

INSERT INTO USERS (USERNAME, EMAIL, FIRST_NAME, LAST_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES ('janedoe', 'jane.doe@example.com', 'Jane', 'Doe', 1, SYSDATE, SYSDATE);

INSERT INTO USERS (USERNAME, EMAIL, FIRST_NAME, LAST_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES ('bobsmith', 'bob.smith@example.com', 'Bob', 'Smith', 0, SYSDATE, SYSDATE);

COMMIT;
